const NABU_PUBLIC_BASE_PATH = process.env.NABU_PUBLIC_BASE_PATH ?? "/api/";


// For local development
// const NABU_SERVER_HOST = "http://localhost";
// const NABU_MEETING_HOST = `${NABU_SERVER_HOST}:8083`
// const NABU_TENANT_HOST = `${NABU_SERVER_HOST}:8082`
// const NABU_USER_HOST = `${NABU_SERVER_HOST}:8081`


const NABU_SERVER_HOST = "https://api.marisolsoftware.com";
const NABU_MEETING_HOST = `${NABU_SERVER_HOST}/api/meeting`
const NABU_TENANT_HOST = `${NABU_SERVER_HOST}/api/tenant`
const NABU_USER_HOST = `${NABU_SERVER_HOST}/api/user`

const NABU_PUBLIC_API_ENDPOINT = NABU_SERVER_HOST
const NABU_USER_API_ENDPOINT = process.env.NABU_USER_API_ENDPOINT ?? `${NABU_USER_HOST}/api/users`;
const NABU_AUTH_API_ENDPOINT = process.env.NABU_AUTH_API_ENDPOINT ?? `${NABU_USER_HOST}/api/auth`;
const NABU_GUEST_API_ENDPOINT = process.env.NABU_GUEST_API_ENDPOINT ?? `${NABU_USER_HOST}/api/guest`;
const NABU_MEETING_API_ENDPOINT = process.env.NABU_MEETING_API_ENDPOINT ?? `${NABU_MEETING_HOST}/api/meetings`;
const NABU_GUEST_MEETING_API_ENDPOINT = process.env.NABU_GUEST_MEETING_API_ENDPOINT ?? `${NABU_MEETING_HOST}/api/guest/meetings`;
const NABU_TENANT_API_ENDPOINT = process.env.NABU_TENANT_API_ENDPOINT ?? `${NABU_TENANT_HOST}/api/`;

const NABU_DOMAIN = process.env.NABU_DOMAIN ?? "https://nabu-io.com";


const IS_DEVELOPMENT_ENV = process.env.NODE_ENV === "development";

export { NABU_PUBLIC_BASE_PATH, NABU_PUBLIC_API_ENDPOINT, NABU_USER_API_ENDPOINT, IS_DEVELOPMENT_ENV, NABU_MEETING_API_ENDPOINT, 
    NABU_AUTH_API_ENDPOINT, NABU_GUEST_MEETING_API_ENDPOINT, NABU_GUEST_API_ENDPOINT, NABU_TENANT_API_ENDPOINT,
    NABU_DOMAIN, NABU_MEETING_HOST, NABU_USER_HOST, NABU_TENANT_HOST, NABU_SERVER_HOST };


