export const awsStreamingLanguages = {
  //'arb': 'Arabic',
  "ar-AE": "Arabic (Gulf)",
  "ca-ES": "Catalan",
  //"yue-CN": "Chinese (Cantonese)",
  "cmn-CN": "Chinese (Mandarin)",
  "cs-CZ": "Czech",
  "da-DK": "Danish",
  "nl-BE": "Dutch (Belgian)",
  "nl-NL": "Dutch",
  "en-AU": "English (Australian)",
  "en-GB": "English (British)",
  "en-IN": "English (Indian)",
  "en-NZ": "English (New Zealand)",
  "en-SG": "English (Singaporean)",
  "en-ZA": "English (South African)",
  "en-US": "English (US)",
  "en-GB-WLS": "English (Welsh)",
  "fi-FI": "Finnish",
  "fr-FR": "French",
  "fr-BE": "French (Belgian)",
  "fr-CA": "French (Canadian)",
  "hi-IN": "Hindi",
  "de-DE": "German",
  "de-AT": "German (Austrian)",
  "de-CH": "German (Swiss standard)",
  "is-IS": "Icelandic",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "ko-KR": "Korean",
  "nb-NO": "Norwegian",
  "pl-PL": "Polish",
  "pt-BR": "Portuguese (Brazilian)",
  "pt-PT": "Portuguese (European)",
  "ro-RO": "Romanian",
  "ru-RU": "Russian",
  "es-ES": "Spanish (Spain)",
  "es-MX": "Spanish (Mexican)",
  "es-US": "Spanish (US)",
  "sv-SE": "Swedish",
  "tr-TR": "Turkish",
  "cy-GB": "Welsh",
};

export const ibmStreamingLanguages = {
  "en-AU": "English (Australian)",
  "en-GB": "English (British)",
  "en-NZ": "English (New Zealand)",
  "en-US": "English (US)",
  "fr-FR": "French",
  "fr-CA": "French (Canadian)",
  "de-DE": "German",
  "it-IT": "Italian",
  "ja-JP": "Japanese",
  "ko-KR": "Korean",
  "pt-BR": "Portuguese (Brazilian)",
  "es-ES": "Spanish (European)",
  "es-US": "Spanish (US)",
};

  export const languagesMap = {
    ...awsStreamingLanguages,
    ...ibmStreamingLanguages,
  };
